// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwdhqucihbcdasbliuxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3ZGhxdWNpaGJjZGFzYmxpdXhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjgxNTMsImV4cCI6MjA2OTY0NDE1M30.MfMDnb5iZSTw3m0JkzhVwMBI-vS0yOfDz77T7p24mT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});